# Even Fibonacci numbers
# Each new term in Fibonacci sequence is generated by adding the prrevious two terms. By starting with 1 and 2, the first
# 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.


def sum_of_even_fibonacci_terms():

    fib_term_1 = 1
    fib_term_2 = 2
    sum_of_even_fib_terms = fib_term_2
    stop = 4000000
    next_term = 0

    while next_term < stop:
        next_term = fib_term_1 + fib_term_2
        fib_term_1 = fib_term_2
        fib_term_2 = next_term
        if next_term % 2 == 0:
            sum_of_even_fib_terms = sum_of_even_fib_terms + next_term

    print("The sum of even Fibonacci terms is " + str(sum_of_even_fib_terms))


sum_of_even_fibonacci_terms()



